---
cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.50"
  - "172.29.240.1,172.29.240.50"
  - "172.29.244.1,172.29.244.50"
  - "172.29.248.1,172.29.248.50"

global_overrides:
  internal_lb_vip_address: 172.29.236.100
  external_lb_vip_address: 172.16.22.77
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
#    - network:
#        container_bridge: "br-vlan"
#        container_type: "veth"
#        container_interface: "eth12"
#        host_bind_override: "eth12"
#        type: "flat"
#        net_name: "flat"
#        group_binds:
#          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - swift_proxy

shared-infra_hosts:
  startcloud:
    # Rabbitmq, and galera are set to multiples to test clustering.
    ip: 172.29.236.100

os-infra_hosts:
  startcloud:
    # Horizon is set to multiple to test clustering. This test only requires x2.
    ip: 172.29.236.100

storage-infra_hosts:
  startcloud:
    ip: 172.29.236.100


identity_hosts:
  startcloud:
    # Keystone is set to multiple to test clustering. This test only requires x2.
    ip: 172.29.236.100

compute_hosts:
  compute01:
    ip: 172.29.236.101
  compute02:
    ip: 172.29.236.102


log_hosts:
  startcloud:
    ip: 172.29.236.100

network_hosts:
  startcloud:
    ip: 172.29.236.100

haproxy_hosts:
  startcloud:
    ip: 172.29.236.100
